version: '3.8'

services:
  flaskapp:
    build: .
    container_name: flaskctfcontainer
    ports:
      - "2000:5000"  # Maps port 2000 on the host to port 5000 in the container
    environment:
      - FLASK_ENV=development
    command: python app.py
